source "https://rubygems.org"
source "https://rubygems.org"

ruby RUBY_VERSION

gem 'github-pages' # helpfully pulls in more than just jekyll

# This will help ensure the proper Jekyll version is running.
#gem "jekyll", "3.8.5"


